# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'final' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for final

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Storage'
  pod 'SDWebImage', '~>3.7'

  target 'finalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'finalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
